package com.firestarterstagss.Models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS_WEB".
 */
public class HeartBeatUsers {

    private Long id;
    private String imageUrl;
    private String username;
    private String password;
    private String coins;
    private String cookie;
    private String csrf_token;

    public HeartBeatUsers() {
    }

    public HeartBeatUsers(Long id) {
        this.id = id;
    }

    public HeartBeatUsers(Long id, String imageUrl, String username, String password, String coins, String cookie, String csrf_token) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.username = username;
        this.password = password;
        this.coins = coins;
        this.cookie=cookie;
        this.csrf_token=csrf_token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public String getCsrf() {
        return csrf_token;
    }

    public void setCsrf(String csrf_token) {
        this.csrf_token = csrf_token;
    }
    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCoins() {
        return coins;
    }

    public void setCoins(String coins) {
        this.coins = coins;
    }

}
